# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbdbaa0efcf16a3cbc4abd32768c382ccb9f1ad9d0af2d441667b68e9e1dcf4e723a570db22bd6a13fee8225cb1de5b0af72c77ecad1e586b3bf5e5d555e3665

test:
  secret_key_base: 4d9090e232a4972636b1a1912398d32734bddc842a750395a8b408c8a049c67a8184e6c5079281f804fbdbc56ba58bbe04e7ebd4f503aa91999b50f062e545cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
